apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  labels:
    app: xbot-ai
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: xbot-ai
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: xbot-ai
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: xbot-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
